# Generated by Django 5.2.12 on 2026-03-17 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_livro_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
