# Generated by Django 5.2.13 on 2026-04-14 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_editora_email_editora_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='editora',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
