# Generated by Django 5.2.13 on 2026-04-14 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_livro_data_publicacao_alter_livro_preco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='quantidade',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
